kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-kube-new
spec:
  selector:
    matchLabels:
      name: hello-kube-new
  template:
    metadata:
      labels:
        name: hello-kube-new
    spec:
      containers:
        - name: hello-kube
          image: paulbouwer/hello-kubernetes:1.10
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: MESSAGE
              value: "Hello from !NEW VERSION! of application"
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: KUBERNETES_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: CONTAINER_IMAGE
              value: paulbouwer/hello-kubernetes:1.10
---
kind: Service
apiVersion: v1
metadata:
  name: hello-kube-new
  labels:
    name: hello-kube-new
spec:
  selector:
    name: hello-kube-new
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-kube-old-v1
spec:
  selector:
    matchLabels:
      name: hello-kube-old-v1
  template:
    metadata:
      labels:
        name: hello-kube-old-v1
    spec:
      containers:
        - name: hello-kube
          image: paulbouwer/hello-kubernetes:1.10
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: MESSAGE
              value: "Hello from !OLD VERSION 1! of application"
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: KUBERNETES_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: CONTAINER_IMAGE
              value: paulbouwer/hello-kubernetes:1.10
            - name: HANDLER_PATH_PREFIX
              value: "v1"
            - name: RENDER_PATH_PREFIX
              value: "v1"
---
kind: Service
apiVersion: v1
metadata:
  name: hello-kube-old-v1
  labels:
    name: hello-kube-old-v1
spec:
  selector:
    name: hello-kube-old-v1
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-kube-old-v2
spec:
  selector:
    matchLabels:
      name: hello-kube-old-v2
  template:
    metadata:
      labels:
        name: hello-kube-old-v2
    spec:
      containers:
        - name: hello-kube
          image: paulbouwer/hello-kubernetes:1.10
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: MESSAGE
              value: "Hello from !OLD VERSION 2! of application"
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: KUBERNETES_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: CONTAINER_IMAGE
              value: paulbouwer/hello-kubernetes:1.10
            - name: HANDLER_PATH_PREFIX
              value: "v2"
            - name: RENDER_PATH_PREFIX
              value: "v2"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-kube-old-v2
  labels:
    name: hello-kube-old-v2
spec:
  selector:
    name: hello-kube-old-v2
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
