---
- hosts: all
  # Run with super privileges
  become: yes
  roles:
    - init
    - docker
    - kubernetes
    # - ngrok
  tasks:
    - name: Create directory for kube.conf
      file:
        path: /etc/sysctl.d
        state: directory
        # mode: '0755'
    
    - name: Create file kube.conf
      file:
        path: /etc/sysctl.d/kube.conf
        state: touch

    - name: Create network bridge
      lineinfile:
        path: /etc/sysctl.d/kube.conf
        state: present
        line: "{{ item }}"
      with_items:
        - net.bridge.bridge-nf-call-ip6tables = 1
        - net.bridge.bridge-nf-call-iptables = 1

    - name: Restart kubelet
      service:
        # state: restarted
        # daemon_reload: yes
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - docker
        - kubelet

    - name: Initialize Kubernetes cluster
      shell: kubeadm init --pod-network-cidr=192.168.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt
    
    - name: Setup kubeconfig for vagrant user
      command: "{{ item }}"
      with_items:
        - mkdir -p /home/vagrant/.kube
        - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
        - chown vagrant:vagrant /home/vagrant/.kube/config