---
- hosts: kube_cluster
  gather_facts: yes
  become: yes
  roles:
    - { role: common, tags: common }
    - { role: docker, tags: docker }
    - { role: kubernetes/common, tags: common }

- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/master, tags: master }

# - hosts: worker
#   gather_facts: yes
#   become: yes
#   roles:
#     - { role: kubernetes/worker, tags: worker }