---
- name: Common setup
  hosts: workers,masters
  become: yes
  roles:
    - init
    - docker
    - kubernetes
    # - ngrok

- name: Master Setup
  become: yes
  hosts: masters
  tasks:
    - import_tasks: master.yaml