---
- name: Reset Kubernetes component
  shell: "kubeadm reset --force"
  register: reset_cluster

- name: Initialize Kubernetes cluster
  when: reset_cluster is succeeded
  shell: |
    kubeadm init --pod-network-cidr=192.168.0.0/16 >> cluster_initialized.txt
  args:
    chdir: $HOME
    creates: cluster_initialized.txt
  register: init_cluster

- name: Create Kubernetes config directory
  file:
    path: "home/vagrant/.kube/"
    state: directory

# - name: Copy admin.conf to Home directory
#   when: init_cluster is succeeded
#   copy:
#     src: "/etc/kubernetes/admin.conf"
#     dest: "home/vagrant/.kube/config"
#     owner: "vagrant" # "{{ ansible_user | default(ansible_user_id) }}"
#     group: "vagrant" # "{{ ansible_user | default(ansible_user_id) }}"
#     mode: 0755
#     remote_src: true
