---
- name: Check if kubeadm has already run
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: Enable and check kubelet service
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes
  register: started_kubelet

- name: Init cluster if needed
  include_tasks: init.yaml
  # when: not kubeadm_ca.stat.exists
  run_once: yes

- name: "Copy config file"
  fetch:
    src: /etc/kubernetes/admin.conf 
    dest: "/home/vagrant/.kube/config"
    flat: yes
  run_once: yes
  ignore_errors: yes