kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: cluster-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    # traefik.ingress.kubernetes.io/router.entrypoints: websecure
    # traefik.ingress.kubernetes.io/router.tls: "true"
    # kubernetes.io/ingress.class: "traefik"
    #traefik.ingress.kubernetes.io/redirect-entry-point: https
    #traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  rules:
    - host: cluster.demo
      http:
        paths:
          - path: /traefik
            pathType: Prefix
            backend:
              service:
                name: traefik-dashboard
                port:
                  number: 8081
          - path: /
            pathType: Exact
            backend:
              service:
                name: kdash
                port:
                  number: 8001
          # - path: /foo
          #   pathType: Exact
          #   backend:
          #     service:
          #       name:  whoami
          #       port:
          #         number: 80
